### ISSUE TITLE
version ipad mac os x

### ISSUE THREAD

**Issue by pc2019** [kunaldodiya/streamly#1]
version mac                                                                                                                                              
 version ios 
thank you
streamly

**Comment by kunaldodiya** [comment]
hello pc2019,
Will you please try to download again. 

Thanks

**Comment by pc2019** [comment]
version for iOS iPad iPhone ios 11

**Comment by kunaldodiya** [comment]
Working on it.. will launch this week. :)

**Comment by pc2019** [comment]
thank you

**Comment by kunaldodiya** [comment]
Welcome, feel free to ask any question again.. close for now :)
