### ISSUE TITLE
apple tv tvos

### ISSUE THREAD

**Issue by pc2019** [kunaldodiya/streamly#2]
version apple tv 4k  streamly
thank you

**Comment by kunaldodiya** [comment]
sure, In todo list now :)

**Comment by pc2019** [comment]
you can not see the quality 4k when I play the movie and series 2160p the video does not come out

**Comment by pc2019** [comment]
<img width="1004" alt="captura de pantalla 2018-04-11 a la s 08 53 59" src="https://user-images.githubusercontent.com/36860727/38621193-f3e7f146-3d65-11e8-92a8-fd82ffd4e06b.png">

**Comment by kunaldodiya** [comment]
Let me check, wait... is it only for 4k or other qualities causing the same issue ????

**Comment by kunaldodiya** [comment]
What links are you playing, whats your ISP configuration.. internet speed ??? playing 4k requires high end internet plan at-least 35mpbs for bufferless streaming, if you don't have that much internet speed I would recommend to go with 1080p instead. :)

**Comment by kunaldodiya** [comment]
Closing since not directly related to bug / issue.
